# ----------------------------
# Makefile Options
# ----------------------------

NAME = lf2crlf
DESCRIPTION = "Ag C Toolchain Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz
LDHAS_ARG_PROCESSING = 1

# ----------------------------

include $(shell cedev-config --makefile)
